//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_WCF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.PetStateHistory = new HashSet<PetStateHistory>();
        }
    
        public int Id { get; set; }
        public string Pet_Name { get; set; }
        public System.DateTime Day_Birth { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Id_Race { get; set; }
        public Nullable<int> Id_Person { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Race Race { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PetStateHistory> PetStateHistory { get; set; }
    }
}
