//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_WCF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pet_Shop_BusinessEntities : DbContext
    {
        public Pet_Shop_BusinessEntities()
            : base("name=Pet_Shop_BusinessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnimalType> AnimalType { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PersonStateHistory> PersonStateHistory { get; set; }
        public virtual DbSet<Pet> Pet { get; set; }
        public virtual DbSet<PetStateHistory> PetStateHistory { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Race> Race { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserData> UserData { get; set; }
    }
}
