//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_WCF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int Id { get; set; }
        public string Password { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> Id_Person { get; set; }
        public Nullable<int> Id_Profile { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
