//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_WCF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pet_Shop_BusinessEntities : DbContext
    {
        public Pet_Shop_BusinessEntities()
            : base("name=Pet_Shop_BusinessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Document_Types> Document_Types { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<Pets> Pets { get; set; }
        public virtual DbSet<Races> Races { get; set; }
        public virtual DbSet<Type_Animals> Type_Animals { get; set; }
    }
}
