//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_WCF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets
    {
        public int Id { get; set; }
        public string Pet_Name { get; set; }
        public System.DateTime Day_Birth { get; set; }
        public Nullable<int> Id_Race { get; set; }
        public string Photo { get; set; }
        public int Id_Person { get; set; }
    
        public virtual Persons Persons { get; set; }
        public virtual Races Races { get; set; }
    }
}
